#!/usr/bin/env python3

from hg100r import get_salt, get_hashed_password

if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument('api_url', type=str)
    parser.add_argument('password', type=str)
    args = parser.parse_args()

    api_url = args.api_url
    password = args.password

    salt = get_salt(api_url=api_url)
    hashed_password = get_hashed_password(password=password, salt=salt)

    print(hashed_password)
