#!/usr/bin/env python3

from hg100r import (
    get_token_with_raw_password,
    get_wan_ipv4,
)

if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument('api_url', type=str)
    parser.add_argument('password', type=str)
    args = parser.parse_args()

    api_url = args.api_url
    password = args.password

    token = get_token_with_raw_password(api_url=api_url, password=password)
    ipv4_addr = get_wan_ipv4(api_url=api_url, token=token)

    print(ipv4_addr)
