#!/usr/bin/env python3

from aoirint_hg100rclient import HG100RClient, interactive_config

if __name__ == '__main__':
  interactive_config()

  hg100r = HG100RClient()

  ipv4_addr = hg100r.get_wan_ipv4()
  print(ipv4_addr)
