#!/usr/bin/env python3

from aoirint_hg100rclient import HG100RClient, interactive_config

if __name__ == '__main__':
  interactive_config()

  hg100r = HG100RClient()

  ret = hg100r.reboot_router()
  print(ret)
