#!/usr/bin/env python3

import os
from hg100r import get_token_with_raw_password, reboot_router
from dotenv import load_dotenv

load_dotenv()

if __name__ == '__main__':
    import argparse

    #parser = argparse.ArgumentParser()
    #parser.add_argument('api_url', type=str)
    #parser.add_argument('password', type=str)
    #args = parser.parse_args()

    #api_url = args.api_url
    #password = args.password

    api_url = os.environ['API_URL']
    password = os.environ['PASSWORD']

    token = get_token_with_raw_password(api_url=api_url, password=password)
    ret = reboot_router(api_url=api_url, token=token)

    print(ret)
