#!/usr/bin/env python3

from hg100r import get_salt

if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument('api_url', type=str)
    args = parser.parse_args()

    api_url = args.api_url

    ret = get_salt(api_url=api_url)

    print(ret)
