#!/usr/bin/env python3

from hg100r import get_token, reboot_router

if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument('api_url', type=str)
    parser.add_argument('hashed_password', type=str)
    args = parser.parse_args()

    api_url = args.api_url
    hashed_password = args.hashed_password

    token = get_token(api_url=api_url, hashed_password=hashed_password)
    ret = reboot_router(api_url=api_url, token=token)

    print(ret)
